### ISSUE TITLE
Filenames in /e107_docs/help/Hungarian contain incorrect characters

### ISSUE THREAD

**Issue by Moc** [e107translations/Hungarian#11]
@yesszus The files in e107_docs/help/Hungarian have html encoded characters in their name. This is incorrect. 

![image](https://user-images.githubusercontent.com/577978/188497567-0ee9448b-2f60-4b19-8456-937d92db1f76.png)

**Comment by yesszus** [comment]
Thks, corrected.

**Comment by Moc** [comment]
Thanks! I can't check it properly now but I think that the file names need to be the same as the English names, otherwise they won't display properly.
